In [1]:
print('hi')

hi

In [1]:
import pandas as pd

In [2]:
bangalore_df = pd.read_excel(r"S:\Car\ML ready data\Bangalore_car_detail.xlsx")
print(bangalore_df.shape)
bangalore_df['City'] = 'Bangalore'
bangalore_df.head()

(1481, 75)

,Unnamed: 0,it,ft,bt,km,transmission,ownerNo,owner,oem,model,...,Super Charger,Front Tread,Rear Tread,Gross Weight,Turning Radius,Top Speed,Acceleration,BoreX Stroke,Ground Clearance Unladen,City
0,0,0,Petrol,Hatchback,120000,Manual,3,3rd Owner,Maruti,Maruti Celerio,...,No,1420mm,1410mm,1250kg,4.7 metres,150 Kmph,15.05 Seconds,73 X 82 mm,NaN,Bangalore
1,1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,...,No,NaN,NaN,1660Kg,5.3 metres,NaN,NaN,79 X 76.5 mm,NaN,Bangalore
2,2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,...,No,1400mm,1420mm,NaN,4.9 meters,150 kmph,14.3 Seconds,77 X 85.8 mm,NaN,Bangalore
3,3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,...,No,1479mm,1493mm,NaN,4.7 metres,172km/hr,14.2 Seconds,NaN,NaN,Bangalore
4,4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,...,No,NaN,NaN,1670kg,5.2 meters,190 Kmph,12 Seconds,69.6 x 82 mm,NaN,Bangalore

In [3]:
bangalore_df.isna().sum()

Unnamed: 0                     0
it                             0
ft                             0
bt                             0
km                             0
                            ...
Top Speed                    672
Acceleration                 633
BoreX Stroke                1098
Ground Clearance Unladen    1394
City                           0
Length: 76, dtype: int64

In [4]:
chennai_df = pd.read_excel(r"S:\Car\ML ready data\Chennai_car_detail.xlsx")
delhi_df = pd.read_excel(r"S:\Car\ML ready data\Delhi_car_detail.xlsx")
hyderabad_df = pd.read_excel(r"S:\Car\ML ready data\Hyderabad_car_detail.xlsx")
jaipur_df = pd.read_excel(r"S:\Car\ML ready data\Jaipur_car_detail.xlsx")
kolkata_df = pd.read_excel(r"S:\Car\ML ready data\Kolkata_car_detail.xlsx")

In [5]:
chennai_df['City'] = 'Chennai'
delhi_df['City'] = 'Delhi'
hyderabad_df['City'] = 'Hyderabad'
jaipur_df['City'] = 'Jaipur'
kolkata_df['City'] = 'Kolkata'

In [6]:
df = pd.concat([bangalore_df,chennai_df,delhi_df,hyderabad_df,jaipur_df,kolkata_df])
print(df.shape) # 
df.City

(8369, 76)

0       Bangalore
1       Bangalore
2       Bangalore
3       Bangalore
4       Bangalore
          ...
1376      Kolkata
1377      Kolkata
1378      Kolkata
1379      Kolkata
1380      Kolkata
Name: City, Length: 8369, dtype: object

In [7]:
df['Comfort & Convenience'].value_counts()

Comfort & Convenience
11    637
10    551
16    520
15    519
17    507
14    450
12    446
13    443
20    390
9     389
19    346
21    332
18    305
23    292
8     229
5     220
22    212
7     196
24    194
27    170
6     167
25    150
29    128
26    122
28     96
0      68
31     59
30     59
2      43
32     37
33     21
3      20
4      18
1      14
34      9
35      7
37      3
Name: count, dtype: int64

In [298]:
relevant_features = [
    "km","transmission","ownerNo","oem","model","modelYear","variantName","price","Registration Year",
    "Insurance Validity","Fuel Type","Seats_x","Kms Driven","RTO","Engine Displacement",
    "Transmission","Year of Manufacture","Features","Comfort & Convenience","Interior","Exterior","Safety",
    "Entertainment & Communication","Engine","Max Power","Torque","Wheel Size","Seats_y","Color",
    "Engine Type","Displacement","Max Torque","No of Cylinder","Values per Cylinder","Fuel Suppy System",
    "Turbo Charger","Length","Width","Height","Wheel Base","Kerb Weight","Gear Box","Drive Type",
    "Seating Capacity","Steering Type","Front Brake Type","Rear Brake Type","Tyre Type","Alloy Wheel Size",
    "No Door Numbers","Cargo Volumn","Mileage","Value Configuration","Compression Ratio","Super Charger",
    "Front Tread","Rear Tread","Gross Weight","Turning Radius","Top Speed","Acceleration",
    "BoreX Stroke","Ground Clearance Unladen",'City'
]

In [299]:
df1 = df[relevant_features]
df1

,km,transmission,ownerNo,oem,model,modelYear,variantName,price,Registration Year,Insurance Validity,...,Super Charger,Front Tread,Rear Tread,Gross Weight,Turning Radius,Top Speed,Acceleration,BoreX Stroke,Ground Clearance Unladen,City
0,120000,Manual,3,Maruti,Maruti Celerio,2015,VXI,â‚¹ 4 Lakh,2015,Third Party insurance,...,No,1420mm,1410mm,1250kg,4.7 metres,150 Kmph,15.05 Seconds,73 X 82 mm,NaN,Bangalore
1,"32,706",Manual,2,Ford,Ford Ecosport,2018,1.5 Petrol Titanium BSIV,â‚¹ 8.11 Lakh,Feb 2018,Comprehensive,...,No,NaN,NaN,1660Kg,5.3 metres,NaN,NaN,79 X 76.5 mm,NaN,Bangalore
2,"11,949",Manual,1,Tata,Tata Tiago,2018,1.2 Revotron XZ,â‚¹ 5.85 Lakh,Sept 2018,Comprehensive,...,No,1400mm,1420mm,NaN,4.9 meters,150 kmph,14.3 Seconds,77 X 85.8 mm,NaN,Bangalore
3,"17,794",Manual,1,Hyundai,Hyundai Xcent,2014,1.2 Kappa S Option,â‚¹ 4.62 Lakh,Dec 2014,Comprehensive,...,No,1479mm,1493mm,NaN,4.7 metres,172km/hr,14.2 Seconds,NaN,NaN,Bangalore
4,"60,000",Manual,1,Maruti,Maruti SX4 S Cross,2015,DDiS 200 Zeta,â‚¹ 7.90 Lakh,2015,Third Party insurance,...,No,NaN,NaN,1670kg,5.2 meters,190 Kmph,12 Seconds,69.6 x 82 mm,NaN,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,"10,000",Manual,1,Maruti,Maruti Celerio,2022,ZXI BSVI,â‚¹ 5.10 Lakh,2022,Third Party insurance,...,NaN,1430,1440,1260,NaN,NaN,NaN,NaN,NaN,Kolkata
1377,"1,20,000",Manual,1,Maruti,Maruti Alto 800,2014,LXI,â‚¹ 1.80 Lakh,2014,Third Party insurance,...,No,1295mm,1290mm,1185kg,4.6 metres,140 kmph,19 Seconds,NaN,NaN,Kolkata
1378,"50,000",Automatic,3,Mercedes-Benz,Mercedes-Benz C-Class,2011,C 200 CGI Elegance,â‚¹ 5.50 Lakh,2011,Third Party insurance,...,No,1549mm,1552mm,2020kg,5.42 metres,230km/hr,8.8 Seconds,NaN,NaN,Kolkata
1379,"40,000",Manual,1,Maruti,Maruti Ritz,2012,ZXi,â‚¹ 1.40 Lakh,2012,Third Party insurance,...,No,1470mm,1480mm,1430kg,4.7 metres,156 Kmph,15 Seconds,NaN,NaN,Kolkata
1380,"1,20,000",Manual,2,Renault,Renault Duster,2017,110PS Diesel RxZ AWD,â‚¹ 5 Lakh,2017,Third Party insurance,...,No,1560mm,1567mm,1889kg,5.2 metres,168 Kmph,14.20 Seconds,NaN,NaN,Kolkata

In [300]:
def convert_to_lakhs(price):
    price = price.replace('â‚¹', '').replace(',', '').strip()
    if 'Crore' in price:
        return float(price.replace('Crore', '').strip()) * 100
    elif 'Lakh' in price:
        return float(price.replace('Lakh', '').strip())     
    else:
        return float(price)/100

In [301]:
df1.loc[:,'price_in_lakhs'] = df1['price'].apply(convert_to_lakhs)

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\3923615973.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.loc[:,'price_in_lakhs'] = df1['price'].apply(convert_to_lakhs)

In [302]:
df1['price_in_lakhs'].describe()

count    8369.000000
mean       18.359159
std        79.364616
min         1.000000
25%         4.040000
50%         6.200000
75%         9.830000
max       997.030000
Name: price_in_lakhs, dtype: float64

In [303]:
print(df1.columns)

Index(['km', 'transmission', 'ownerNo', 'oem', 'model', 'modelYear',
       'variantName', 'price', 'Registration Year', 'Insurance Validity',
       'Fuel Type', 'Seats_x', 'Kms Driven', 'RTO', 'Engine Displacement',
       'Transmission', 'Year of Manufacture', 'Features',
       'Comfort & Convenience', 'Interior', 'Exterior', 'Safety',
       'Entertainment & Communication', 'Engine', 'Max Power', 'Torque',
       'Wheel Size', 'Seats_y', 'Color', 'Engine Type', 'Displacement',
       'Max Torque', 'No of Cylinder', 'Values per Cylinder',
       'Fuel Suppy System', 'Turbo Charger', 'Length', 'Width', 'Height',
       'Wheel Base', 'Kerb Weight', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'Front Brake Type',
       'Rear Brake Type', 'Tyre Type', 'Alloy Wheel Size', 'No Door Numbers',
       'Cargo Volumn', 'Mileage', 'Value Configuration', 'Compression Ratio',
       'Super Charger', 'Front Tread', 'Rear Tread', 'Gross Weight',
       'Turning Radius', 'Top Speed', 'Acceleration', 'BoreX Stroke',
       'Ground Clearance Unladen', 'City', 'price_in_lakhs'],
      dtype='object')

In [304]:
df1.loc[:,'km'] = df1['km'].str.replace(',','')

In [305]:

df1['km'] = df1['km'].astype(float)
df1['ownerNo'] = df1['ownerNo'].astype(float)
df1['modelYear'] = df1['modelYear'].astype(float)
df1['price_in_lakhs'] = df1['price_in_lakhs'].astype(float)
df1['Year of Manufacture'] = df1['Year of Manufacture'].astype(float)
df1['Features'] = df1['Features'].astype(float)
df1['Comfort & Convenience'] = df1['Comfort & Convenience'].astype(float)
df1['Values per Cylinder'] = df1['Values per Cylinder'].astype(float)
df1['No of Cylinder'] = df1['No of Cylinder'].astype(float)
df1['Interior'] = df1['Interior'].astype(float)
df1['Exterior'] = df1['Exterior'].astype(float)


df1['Safety'] = df1['Safety'].astype(float)
df1['Entertainment & Communication'] = df1['Entertainment & Communication'].astype(float)

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['km'] = df1['km'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ownerNo'] = df1['ownerNo'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['modelYear'] = df1['modelYear'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['price_in_lakhs'] = df1['price_in_lakhs'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Year of Manufacture'] = df1['Year of Manufacture'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Features'] = df1['Features'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Comfort & Convenience'] = df1['Comfort & Convenience'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Values per Cylinder'] = df1['Values per Cylinder'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['No of Cylinder'] = df1['No of Cylinder'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Interior'] = df1['Interior'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Exterior'] = df1['Exterior'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Safety'] = df1['Safety'].astype(float)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1069540141.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Entertainment & Communication'] = df1['Entertainment & Communication'].astype(float)

In [306]:
df1['Registration Year'] = df1['Registration Year'].astype(str)

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1530573367.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Registration Year'] = df1['Registration Year'].astype(str)

In [307]:
df1['Registration Year'].dtype

dtype('O')

In [308]:
df1[['Registration Month','Registration Year New']] = df1['Registration Year'].str.split(' ',expand=True)
df1['Registration Year New'] = df1['Registration Year New'].astype(float)
df1['Registration Year New'].value_counts()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1110492372.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[['Registration Month','Registration Year New']] = df1['Registration Year'].str.split(' ',expand=True)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1110492372.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[['Registration Month','Registration Year New']] = df1['Registration Year'].str.split(' ',expand=True)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1110492372.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Registration Year New'] = df1['Registration Year New'].astype(float)

Registration Year New
2018.0    778
2017.0    743
2019.0    622
2016.0    614
2021.0    502
2020.0    473
2014.0    419
2015.0    398
2022.0    346
2013.0    229
2012.0    184
2011.0    127
2010.0    108
2023.0     79
2009.0     32
2008.0     26
2007.0     14
2006.0      7
2005.0      6
2004.0      5
2002.0      3
2003.0      2
Name: count, dtype: int64

In [309]:
df1.drop(['Engine','Transmission','RTO','Kms Driven','price','Seats_x','Displacement',
          'Max Torque','Registration Month'],axis=1,inplace=True)

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\2282047627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(['Engine','Transmission','RTO','Kms Driven','price','Seats_x','Displacement',

In [310]:
df1['Wheel Size'] = df1['Wheel Size'].astype(str)
df1['Wheel Size'] = df1['Wheel Base'].str.replace('R','',regex=True).replace('mm','',regex=True)

df1['Wheel Size'].value_counts()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\2194207345.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Wheel Size'] = df1['Wheel Size'].astype(str)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\2194207345.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Wheel Size'] = df1['Wheel Base'].str.replace('R','',regex=True).replace('mm','',regex=True)

Wheel Size
2450      650
2600      447
2425      423
2520      394
2380      371
         ...
2,400       1
2795        1
2825        1
2,480       1
2622        1
Name: count, Length: 228, dtype: int64

In [311]:
df1['Length'] = df1['Length'].astype(str)
df1['Length'] = df1['Length'].str.replace('mm','',regex=True)

df1['Length'].value_counts()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\2306317603.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Length'] = df1['Length'].astype(str)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\2306317603.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Length'] = df1['Length'].str.replace('mm','',regex=True)

Length
3995      1029
4440       363
3765       312
3985       245
4585       204
          ...
5215         1
4425         1
4,530        1
5015         1
4470         1
Name: count, Length: 372, dtype: int64

In [312]:
df1['Width'] = df1['Width'].astype(str)
df1['Width'] = df1['Width'].str.replace('mm','',regex=True)
df1.Width.value_counts()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\492694699.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Width'] = df1['Width'].astype(str)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\492694699.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Width'] = df1['Width'].str.replace('mm','',regex=True)

Width
1695      598
1735      516
1745      337
1660      335
1680      307
         ...
2145        1
1923        1
1,726       1
1,710       1
2042        1
Name: count, Length: 270, dtype: int64

In [313]:
df1['Height'] = df1['Height'].astype(str)
df1['Height'] = df1['Height'].str.replace('mm','',regex=True)

df1['Height'].value_counts()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\925480852.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Height'] = df1['Height'].astype(str)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\925480852.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Height'] = df1['Height'].str.replace('mm','',regex=True)

Height
1530      442
1520      439
1475      423
1505      388
1510      326
         ...
1624        1
1600        1
1288        1
1,505       1
1308        1
Name: count, Length: 300, dtype: int64

In [314]:
df1['Wheel Base'] = df1['Wheel Base'].astype(str)
df1['Wheel Base'] = df1['Wheel Base'].str.replace('mm','',regex=True)
df1['Wheel Base'].value_counts()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\3837866299.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Wheel Base'] = df1['Wheel Base'].astype(str)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\3837866299.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Wheel Base'] = df1['Wheel Base'].str.replace('mm','',regex=True)

Wheel Base
2450      650
2600      447
2425      423
2520      394
2380      371
         ...
2,400       1
2795        1
2825        1
2,480       1
2622        1
Name: count, Length: 229, dtype: int64

In [315]:
df1['Gear Box'].value_counts()

Gear Box
5 Speed              4384
6 Speed              1078
5-Speed               560
7 Speed               272
6-Speed               236
                     ...
9 -speed                1
8                       1
8-speed tiptronic       1
7-Speed S tronic        1
eCVT                    1
Name: count, Length: 113, dtype: int64

In [316]:
import re
df1['Gear Box'] = df1['Gear Box'].astype(str)
def clean_gearbox(gear_box):
  """
  Extracts the gear number from the 'Gear Box' string.

  Args:
      gear_box (str): The string containing the gear information.

  Returns:
      str: The extracted gear number (or an empty string if not found).
  """
  if pd.isna(gear_box):  # Check for missing values (NaN)
    return ""

  pattern = r"^\d"  # Match one or more digits at the beginning of the string
  match = re.search(pattern, gear_box)
  if match:
    return match.group()
  else:
    return ""
df1['Gear'] = df1['Gear Box'].apply(clean_gearbox)
df1['Gear'].value_counts()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\2194434718.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Gear Box'] = df1['Gear Box'].astype(str)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\2194434718.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Gear'] = df1['Gear Box'].apply(clean_gearbox)

Gear
5    5327
6    1622
7     437
      340
8     325
4     177
9     137
1       4
Name: count, dtype: int64

In [317]:
df1.Gear.isna().sum()

np.int64(0)

In [318]:
df['Alloy Wheel Size'].value_counts()

Alloy Wheel Size
16     1520
15     1052
17      846
14      682
13      375
18      371
R16     144
19      106
12       86
R15      76
R17      57
R18      46
20       42
R14       8
21        7
R19       5
R20       1
Name: count, dtype: int64

In [319]:
def clean_wheel_size(size):
  
  if pd.isna(size):  # Check for missing values (NaN)
    return size

  pattern = r"^R?(\d+)"  # Match optional 'R' followed by one or more digits
  match = re.search(pattern, size)
  if match:
    return match.group(1)  # Extract the captured digit group
  else:
    return size

In [320]:
df1['Alloy Wheel Size'] = df1['Alloy Wheel Size'].astype(str)
df1['Alloy Wheel Size'] = df1['Alloy Wheel Size'].apply(clean_wheel_size)
df1['Alloy Wheel Size'].value_counts()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\4185012328.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Alloy Wheel Size'] = df1['Alloy Wheel Size'].astype(str)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\4185012328.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Alloy Wheel Size'] = df1['Alloy Wheel Size'].apply(clean_wheel_size)

Alloy Wheel Size
nan    2945
16     1664
15     1128
17      903
14      690
18      417
13      375
19      111
12       86
20       43
21        7
Name: count, dtype: int64

In [321]:
optional_dropping_columns = ['Front Brake Type','Rear Brake Type','Tyre Type','Alloy Wheel Size',
                             'Cargo Volumn','Ground Clearance Unladen', 'Kerb Weight']
df1.drop(optional_dropping_columns, axis=1, inplace=True)

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1561184444.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(optional_dropping_columns, axis=1, inplace=True)

In [322]:
df1['Mileage'] = df1['Mileage'].astype(str)
df1['Mileage'] = df1['Mileage'].str.replace('kmpl','',regex=True).str.replace('km/kg','',regex=True)

df1['Mileage'].value_counts()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1572173208.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Mileage'] = df1['Mileage'].astype(str)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\1572173208.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Mileage'] = df1['Mileage'].str.replace('kmpl','',regex=True).str.replace('km/kg','',regex=True)

Mileage
18.9      333
nan       285
21.4      209
18.6      206
17        173
         ...
17.99       1
21.49       1
18.33       1
9.4         1
12.98       1
Name: count, Length: 497, dtype: int64

In [323]:
df1['Super Charger'].value_counts()

Super Charger
No     6363
Yes      15
yes       4
NO        1
no        1
Name: count, dtype: int64

In [324]:
def clean_super_charger(charger):
  if pd.isna(charger):  # Check for missing values (NaN)
    return ""

  if 'Yes' in charger:
    return 'Yes'
  else:
    return 'No'
df1['Super Charger'] = df1['Super Charger'].apply(clean_super_charger)
df1['Super Charger'].value_counts()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\65716538.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Super Charger'] = df1['Super Charger'].apply(clean_super_charger)

Super Charger
No     6369
       1985
Yes      15
Name: count, dtype: int64

In [325]:
df1['Turning Radius'] = df1['Turning Radius'].astype(str)
df1['Turning Radius'] = df1['Turning Radius'].str.replace('m','',regex=True).str.replace('mm','',regex=True).replace("etres",'',regex=True).replace('M','',regex=True)
df1['Turning Radius'].value_counts()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\3577598514.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Turning Radius'] = df1['Turning Radius'].astype(str)
C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\3577598514.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Turning Radius'] = df1['Turning Radius'].str.replace('m','',regex=True).str.replace('mm','',regex=True).replace("etres",'',regex=True).replace('M','',regex=True)

Turning Radius
nan       1588
5.3        703
5.2        549
4.8        498
4.7        408
          ...
13           1
4.6          1
4.95         1
5.03         1
5.45         1
Name: count, Length: 132, dtype: int64

In [326]:
df1.columns

Index(['km', 'transmission', 'ownerNo', 'oem', 'model', 'modelYear',
       'variantName', 'Registration Year', 'Insurance Validity', 'Fuel Type',
       'Engine Displacement', 'Year of Manufacture', 'Features',
       'Comfort & Convenience', 'Interior', 'Exterior', 'Safety',
       'Entertainment & Communication', 'Max Power', 'Torque', 'Wheel Size',
       'Seats_y', 'Color', 'Engine Type', 'No of Cylinder',
       'Values per Cylinder', 'Fuel Suppy System', 'Turbo Charger', 'Length',
       'Width', 'Height', 'Wheel Base', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'No Door Numbers', 'Mileage',
       'Value Configuration', 'Compression Ratio', 'Super Charger',
       'Front Tread', 'Rear Tread', 'Gross Weight', 'Turning Radius',
       'Top Speed', 'Acceleration', 'BoreX Stroke', 'City', 'price_in_lakhs',
       'Registration Year New', 'Gear'],
      dtype='object')

In [328]:
df1['City'].value_counts()

City
Delhi        1485
Hyderabad    1483
Bangalore    1481
Chennai      1419
Kolkata      1381
Jaipur       1120
Name: count, dtype: int64

In [ ]:
df1['Value Configuration'].value_counts()

Value Configuration
DOHC                    4701
SOHC                    1259
DOHC                      74
undefined                 32
DOHC with VIS             14
iDSI                      11
DOHC with VGT              5
16-valve DOHC layout       3
16 Modules 48 Cells        2
23 Modules 69 Cells        2
DOHC with TIS              1
VTEC                       1
SOHC                       1
Name: count, dtype: int64

In [336]:
categorical_features = ['transmission','oem','model','modelYear','variantName','Registration Year New',
                        'Insurance Validity','Fuel Type','Year of Manufacture','Engine Displacement',
                        'Max Power','Torque','Color','Engine Type','Fuel Suppy System','Turbo Charger',
                        'Drive Type','Steering Type','Value Configuration','Compression Ratio',
                        'Super Charger','Front Tread','Rear Tread','Gross Weight','Turning Radius',
                         'Top Speed','Acceleration','BoreX Stroke','City']

In [330]:
df1.isna().sum()

km                                  1
transmission                        0
ownerNo                             0
oem                                 0
model                               0
modelYear                           0
variantName                         0
Registration Year                   0
Insurance Validity                  4
Fuel Type                           0
Engine Displacement                 4
Year of Manufacture                20
Features                            0
Comfort & Convenience               0
Interior                            0
Exterior                            0
Safety                              0
Entertainment & Communication       0
Max Power                          65
Torque                             65
Wheel Size                        167
Seats_y                             7
Color                               5
Engine Type                       304
No of Cylinder                     36
Values per Cylinder                56
Fuel Suppy System                1747
Turbo Charger                    1086
Length                              0
Width                               0
Height                              0
Wheel Base                          0
Gear Box                            0
Drive Type                       1618
Seating Capacity                    7
Steering Type                     258
No Door Numbers                    13
Mileage                             0
Value Configuration              2263
Compression Ratio                6499
Super Charger                       0
Front Tread                      3525
Rear Tread                       3533
Gross Weight                     4481
Turning Radius                      0
Top Speed                        3814
Acceleration                     3576
BoreX Stroke                     6022
City                                0
price_in_lakhs                      0
Registration Year New            2652
Gear                                0
dtype: int64

In [333]:
df2 = df1.fillna(method='bfill',axis=0)
df2.isna().sum()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\2676255343.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2 = df1.fillna(method='bfill',axis=0)

km                                0
transmission                      0
ownerNo                           0
oem                               0
model                             0
modelYear                         0
variantName                       0
Registration Year                 0
Insurance Validity                0
Fuel Type                         0
Engine Displacement               0
Year of Manufacture               0
Features                          0
Comfort & Convenience             0
Interior                          0
Exterior                          0
Safety                            0
Entertainment & Communication     0
Max Power                         0
Torque                            0
Wheel Size                        0
Seats_y                           0
Color                             0
Engine Type                       0
No of Cylinder                    0
Values per Cylinder               0
Fuel Suppy System                 0
Turbo Charger                     0
Length                            0
Width                             0
Height                            0
Wheel Base                        0
Gear Box                          0
Drive Type                        0
Seating Capacity                  0
Steering Type                     0
No Door Numbers                   0
Mileage                           0
Value Configuration               0
Compression Ratio                 2
Super Charger                     0
Front Tread                       0
Rear Tread                        0
Gross Weight                      0
Turning Radius                    0
Top Speed                         0
Acceleration                      0
BoreX Stroke                      5
City                              0
price_in_lakhs                    0
Registration Year New            43
Gear                              0
dtype: int64

In [335]:
df2.columns

Index(['km', 'transmission', 'ownerNo', 'oem', 'model', 'modelYear',
       'variantName', 'Registration Year', 'Insurance Validity', 'Fuel Type',
       'Engine Displacement', 'Year of Manufacture', 'Features',
       'Comfort & Convenience', 'Interior', 'Exterior', 'Safety',
       'Entertainment & Communication', 'Max Power', 'Torque', 'Wheel Size',
       'Seats_y', 'Color', 'Engine Type', 'No of Cylinder',
       'Values per Cylinder', 'Fuel Suppy System', 'Turbo Charger', 'Length',
       'Width', 'Height', 'Wheel Base', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'No Door Numbers', 'Mileage',
       'Value Configuration', 'Compression Ratio', 'Super Charger',
       'Front Tread', 'Rear Tread', 'Gross Weight', 'Turning Radius',
       'Top Speed', 'Acceleration', 'BoreX Stroke', 'City', 'price_in_lakhs',
       'Registration Year New', 'Gear'],
      dtype='object')

In [338]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df2[categorical_features] = df2[categorical_features].apply(lambda col: le.fit_transform(col))
df2.drop('Registration Year',axis=1,inplace=True)

,km,transmission,ownerNo,oem,model,modelYear,variantName,Insurance Validity,Fuel Type,Engine Displacement,...,Rear Tread,Gross Weight,Turning Radius,Top Speed,Acceleration,BoreX Stroke,City,price_in_lakhs,Registration Year New,Gear
0,32706.0,1,3.0,20,160,20,1806,5,4,148,...,32,13,25,40,135,29,0,4.00,16,5
1,32706.0,1,2.0,6,50,23,288,2,4,44,...,33,108,69,41,122,99,0,8.11,16,5
2,11949.0,1,1.0,29,273,23,129,2,4,14,...,33,112,36,41,122,77,0,5.85,16,5
3,17794.0,1,1.0,9,87,19,101,2,4,12,...,63,112,25,125,119,15,0,4.62,12,5
4,60000.0,1,1.0,20,178,20,987,5,1,15,...,39,112,59,163,55,15,0,7.90,15,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,10000.0,1,1.0,20,160,27,2051,5,4,148,...,36,15,131,21,177,166,5,5.10,22,5
1377,120000.0,1,1.0,20,155,19,1268,5,4,141,...,13,7,20,21,177,166,5,1.80,22,5
1378,50000.0,0,3.0,21,197,16,891,5,4,59,...,116,191,79,246,282,166,5,5.50,22,7
1379,40000.0,1,1.0,20,175,17,2069,5,4,12,...,55,40,25,65,133,166,5,1.40,22,5
1380,120000.0,1,2.0,27,236,22,460,5,1,36,...,129,160,58,111,121,166,5,5.00,22,6

In [339]:
#Randrom Forest Regressor
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

In [342]:
df2.drop('Wheel Base',axis=1,inplace=True)

In [347]:
df2.drop('Wheel Size',axis=1,inplace=True)

In [352]:
df2.drop(['Length','Width','Height'],axis=1,inplace=True)

In [355]:
df2.drop(['Gear Box'],axis=1,inplace=True)

In [360]:
object_columns = df2.select_dtypes(include=['object']).columns
object_columns

Index(['Mileage', 'Gear'], dtype='object')

In [363]:
df2['Mileage'] = df2['Mileage'].astype(float)

In [364]:
df2.drop('Gear',axis=1,inplace=True)

In [365]:
from sklearn.model_selection import train_test_split

X = df2.drop('price_in_lakhs',axis=1)
y = df2['price_in_lakhs']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((6695, 43), (1674, 43), (6695,), (1674,))

In [366]:
model.fit(X_train,y_train)

RandomForestRegressor()

In [367]:
y_pred = model.predict(X_test)
y_pred

array([ 9.4911,  2.6269,  3.7572, ..., 15.6849,  8.7058,  6.1137])

In [368]:
#accuracy

from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

0.2731239003656266

In [99]:
categorical_features = df1.select_dtypes(include=['object']).columns
categorical_features

Index(['transmission', 'oem', 'model', 'variantName', 'Registration Year',
       'Insurance Validity', 'Fuel Type', 'Seats_x', 'Kms Driven', 'RTO',
       'Engine Displacement', 'Transmission', 'Engine', 'Max Power', 'Torque',
       'Wheel Size', 'Color', 'Engine Type', 'Max Torque', 'Fuel Suppy System',
       'Turbo Charger', 'Length', 'Width', 'Height', 'Wheel Base',
       'Kerb Weight', 'Gear Box', 'Drive Type', 'Steering Type',
       'Front Brake Type', 'Rear Brake Type', 'Tyre Type', 'Alloy Wheel Size',
       'Cargo Volumn', 'Mileage', 'Value Configuration', 'Compression Ratio',
       'Super Charger', 'Front Tread', 'Rear Tread', 'Gross Weight',
       'Turning Radius', 'Top Speed', 'Acceleration', 'BoreX Stroke',
       'Ground Clearance Unladen', 'Registration Month'],
      dtype='object')

In [100]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1[categorical_features] = df1[categorical_features].apply(lambda col: le.fit_transform(col))
df1

C:\Users\Hp\AppData\Local\Temp\ipykernel_7212\3887913292.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[categorical_features] = df1[categorical_features].apply(lambda col: le.fit_transform(col))

,km,transmission,ownerNo,oem,model,modelYear,variantName,Registration Year,Insurance Validity,Fuel Type,...,Rear Tread,Gross Weight,Turning Radius,Top Speed,Acceleration,BoreX Stroke,Ground Clearance Unladen,price_in_lakhs,Registration Month,Registration Year New
0,NaN,1,3.0,20,160,2015.0,1806,13,5,4,...,32,13,33,40,135,29,26,4.00,13,NaN
1,32706.0,1,2.0,6,50,2018.0,288,86,2,4,...,191,108,102,288,312,99,26,8.11,25,2018.0
2,11949.0,1,1.0,29,273,2018.0,129,227,2,4,...,33,314,49,41,122,77,26,5.85,33,2018.0
3,17794.0,1,1.0,9,87,2014.0,101,67,2,4,...,63,314,33,125,119,166,26,4.62,24,2014.0
4,60000.0,1,1.0,20,178,2015.0,987,13,5,1,...,191,112,83,163,55,15,26,7.90,13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,10000.0,1,1.0,20,160,2022.0,2051,20,5,4,...,36,15,186,288,312,166,26,5.10,20,NaN
1377,120000.0,1,1.0,20,155,2014.0,1268,12,5,4,...,13,7,23,21,177,166,26,1.80,12,NaN
1378,50000.0,0,3.0,21,197,2011.0,891,9,5,4,...,116,191,114,246,282,166,26,5.50,9,NaN
1379,40000.0,1,1.0,20,175,2012.0,2069,10,5,4,...,55,40,33,65,133,166,26,1.40,10,NaN
1380,120000.0,1,2.0,27,236,2017.0,460,15,5,1,...,129,160,84,111,121,166,26,5.00,15,NaN

In [101]:
new_categorical_features = df1.select_dtypes(include=['object']).columns
new_categorical_features

Index([], dtype='object')

In [102]:
print(df1.columns)

Index(['km', 'transmission', 'ownerNo', 'oem', 'model', 'modelYear',
       'variantName', 'Registration Year', 'Insurance Validity', 'Fuel Type',
       'Seats_x', 'Kms Driven', 'RTO', 'Engine Displacement', 'Transmission',
       'Year of Manufacture', 'Features', 'Comfort & Convenience', 'Interior',
       'Exterior', 'Safety', 'Entertainment & Communication', 'Engine',
       'Max Power', 'Torque', 'Wheel Size', 'Seats_y', 'Color', 'Engine Type',
       'Displacement', 'Max Torque', 'No of Cylinder', 'Values per Cylinder',
       'Fuel Suppy System', 'Turbo Charger', 'Length', 'Width', 'Height',
       'Wheel Base', 'Kerb Weight', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'Front Brake Type',
       'Rear Brake Type', 'Tyre Type', 'Alloy Wheel Size', 'No Door Numbers',
       'Cargo Volumn', 'Mileage', 'Value Configuration', 'Compression Ratio',
       'Super Charger', 'Front Tread', 'Rear Tread', 'Gross Weight',
       'Turning Radius', 'Top Speed', 'Acceleration', 'BoreX Stroke',
       'Ground Clearance Unladen', 'price_in_lakhs', 'Registration Month',
       'Registration Year New'],
      dtype='object')

In [103]:
df1['BoreX Stroke'].value_counts()

BoreX Stroke
166    6022
36      212
13      150
21      129
11      117
       ...
136       1
145       1
163       1
130       1
88        1
Name: count, Length: 167, dtype: int64

In [104]:
df1.isna().sum()

km                             1
transmission                   0
ownerNo                        0
oem                            0
model                          0
                            ...
BoreX Stroke                   0
Ground Clearance Unladen       0
price_in_lakhs                 0
Registration Month             0
Registration Year New       2652
Length: 65, dtype: int64

In [105]:
df1['Seats_x'].value_counts()

Seats_x
3    7354
5     728
4     103
2      93
6      62
7      11
1       7
8       6
0       5
Name: count, dtype: int64

In [106]:
df1.dtypes

km                          float64
transmission                  int64
ownerNo                     float64
oem                           int64
model                         int64
                             ...
BoreX Stroke                  int64
Ground Clearance Unladen      int64
price_in_lakhs              float64
Registration Month            int64
Registration Year New       float64
Length: 65, dtype: object

In [107]:
df1['Top Speed'].value_counts()

Top Speed
288    3814
104     315
139     276
116     216
175     148
       ...
44        1
118       1
161       1
240       1
282       1
Name: count, Length: 289, dtype: int64